---
title: "Revision history for repwr repository"
author: "Nathan (Nat) Goodman"
date: "November 7, 2018"
output:
  html_document: default
  github_document:
    html_preview: no
  pdf_document: default
linkcolor: cyan
citecolor: green
urlcolor: blue
---
<!-- NEWS.md is generated from NEWS.Rmd. Please edit that file -->

## Release 1.30 2018-11-07

Supports [supplementary material](https://natgoodman.github.io/repwr/resigsupp.stable.html) (`resigsupp.Rmd`) for the shortened blog post with results that didn't fit in the published post for reasons of space or pedagogy

New files

-	`R/doc_resigsupp.R` generates figures and tables for resig supplement
- `R/docfun_resig.R` contains functions used by `doc_resig`; extracted from `R/doc_resig.R`
-	`R/docfun_resigsupp.R` contains functions used by `doc_resigsupp`; adapted from `R/docfun_resig.R`

Deleted files

- `R/doc_xperiment.R` was just a stub that became obsolete

Major code changes

- New mechanism for generating figure and table names
    - names may have document-specific prefix, be section-specific, and occur in blocks with incrementing suffixes (e.g., S2-1a)
    - also handles names for 'extra' figures, ie, ones that don't appear in the document
 - New scheme for running sections in `doc_XXX` functions
     - runs sections in `sapply` loop to allow uniform per-section initialization and setup
     - supports new figure and table names
- Doc-specific initialization moved from `init` to `init_doc` in `R/init.R`

Changed files

- `R/datman.R`
    - `filename_fig`, `figname`, `filename_tbl`, `tblname` implement new figure and table names 
    - extends `filename` to handle NULL components

- `R/doc.R`
    - `dodoc` uses `wrap_fun` to parcel parameters between `init`, `init_doc`, `doc_XXX` function
    - `dofig` and `dotbl` use new figure and table names
    - `figinc`, `tblinc`, etc. manage figure and table names
    - `dofig` uses `wrap_fun` to pass correct parameters to `figfun`

- `R/doc_readme.R`, `R/doc_repwr.R`, 
    - uses new scheme for running sections

- `R/doc_resig.R`
    - uses new scheme for running sections
    - uses `xdata_near` to generate data for nearexact case
    - removed code for functions called by `doc_resig` - moved to `R/docfun_resig.R`
    - removed code for supplement - moved to `R/doc_resigsupp.R`

- `R/init.R`
    - moved doc-specific initialization from `init` to `init_doc`
    - `init_doc` includes initialization for new figure and table names

- `R/plot.R`
    - renamed `legend.where` to `legend` throughout - that's what `doc_XXX` functions call it
    - when called the old way, `legend` matched `legend.where` and all was good. 
    - with `wrap_fun` doesn’t happen because code looks for exact parameter name
    - change arguments to all top-level functions for new figure names
    - fix recurrent bugs that cause matrices to become vectors when selecting single row or column
    - fix bug in `ragm_legend` that caused labels to misalign

- `R/repwr.R`, `R/resig.R`
    - `run` uses `wrap_fun` to parcel parameters between `init`, `dodata`, `dodoc`

- `R/sim_resig.R`
    - `doposr` creates `bias1 posr` needed by resig supplement

- `R/util.R`
    - `wrap_fun` propagates locals and dots (...) to called function
    - `ucfirst` upper-cases first letter of string
    - extends `cq` to handle more atomic types

- `R/Xperiment/detl_conditional.R`, `R/Xperiment/detl_handcrafted.R`
    - port to new `run`, `init` schemes

- `R/Xperiment/hack_proptrue.R`, `R/Xperiment/uri_answer01.R`
    - port to new `run`, `init`, section-running schemes

## Release 1.21 2018-09-27

Fixed typos and restored code accidentally deleted in version 1.20

## Release 1.20 2018-09-26

Supports shortened blog post, [Systematic Replication May Make Many Mistakes](https://natgoodman.github.io/repwr/resig.stable.html) (`resig.Rmd`), kindly posted by Bob Reed on [The Replication Network](https://replicationnetwork.com/2018/09/28/goodman-systematic-replication-may-make-many-mistakes/)

New files

- `R/doc_resig.R` generates figures and tables for resig blog post
- `R/sim_resig.R` like `R/sim.R` but only computes measures needed for resig blog post: `sig1`, `sig2`, `sdir`
- `R/resig.R` like `R/repwr.R` but loads resig-specific files

Code changes

- Many changes to `R/plot.R` to support resig blog post:
    - Added 'plotratm' function to plot multiple rates for a single measure
    - Added 'spline' smoothing method
    - Added more line properties to 'extra' vertical and horizontal lines. Still a hack that will need further cleanup
    - Added specialized function for resig figure titles
    - Added ability to omit legend
    - Added `plot.cutoff` control consistently to all top level functions
    - Added `col` parameter to all `plotXXXm` functions to set colors for rate

- Added spline smoothing method to all line plotting functions. Uses R's `smooth.spline`

Bug fixes

- Fixed bug due to `apply` converting single row matrix into vector. sigh... Bug was present in several functions

## Release 1.11 2018-08-31

Supports third draft blog post [Systematic Replication Has Limited Power to Detect Bad Science](https://natgoodman.github.io/repwr/repwr.stable.html) (`repwr.Rmd`).

Document changes

- Blog post (`repwr.Rmd`)
    - Added reference to new systematic replication study just published in Nature Human Behavior
    - Deleted final paragraph with Oprah Winfrey quote: not really on-target
    - Added words on posting comments using GitHub Issue Tracker

## Release 1.10 2018-08-22

Supports second draft blog post [Systematic Replication Has Limited Power to Detect Bad Science](https://natgoodman.github.io/repwr/repwr.stable.html) (`repwr.Rmd`).

Document changes

- Blog post (`repwr.Rmd`)
    - Changed title and added words in the Abstract, Introduction, and Discussion to clarify that the post is about *systematic* replications
    - Added references suggested by readers
    - Added more emphasis to David Colquhoun's point about taking into account the prior probability that studies are true 
    - Added terms suggested by readers: *direct replication*, *conceptual replication*, *study heterogeneity*
    - Added sentence noting that "measures answer different questions, but all appear in papers or posts as tests to accept or reject replications" as suggested by reader

- README
    - Reflect changes to `dodata` and `dodoc` interfaces and `clean` default
    - Removed mention of technical notes document - no point making promises I may not keep
    - Added mention of previous version (1.00) of blog post

Design changes

- Refactored data aggregation code into `data_agg` function and `drag` data type
- Added support for experimental sandbox code, mainly to document sandbox projects
- Improved `dodata`, `dodoc` interfaces. These are top-level functions called by `run`. May also be called directly
    - Moved processing of default values to `init`
    - Moved `figscreen`, `fignew` parameters from `dodoc` to `init` because they depend on `doc` which is not fully set until `init`
    - In `dodoc`, set default for `docfun` after `init` for same reason
    - In `dodoc`, prefix match xperiment `doc` for same reason
    - Added `need.init` parameter to avoid rerunning `init` when called from run
    - Set default for `need.init` to `TRUE` so top-level calls will run `init` 
- Moved `rate.type` conversion from `drat_order` to `data_rate`; this is the natural place where I expect it to be
- Added ability to save figures to files without first plotting to screen; much faster!

Changes to directory and repo organization

- Added version-specific copies of blog post documents
- Removed data files from repo. I was only storing files needed to draw figures which seemed like good idea but interacts poorly with caching scheme. With the data files gone, user has to generate data before drawing figures
- Generated figures for non-default values of `m`; just for completeness

Bug fixes 

- Setting `from.type`, `relto.type` in plot functions does not select desired posr
    - Caused by conflicting parameter defaults. `plotrate` and related functions provide default values for `from.type`, `relto.type`, `posr.id` and pass the values to called functions. By the time the values make it to `get_posr` which does the work, it looks like all three parameters were set by the original caller. `get_posr` calls `casename_posr` which lets `id` supersede the others
    - Opted for simplest solution. Always use `posr.id` to identify `posr`. Give up trying to use `from.type`, `relto.type`
- Make sure `data.list` exists before trying to delete elements

Code cleanup

- Added `vhlty` parameter to plot functions to set line type for extra vertical and horizontal lines; quick hack, not very general
- Consolidated documentation (still just in comments, sorry) for all aggregate plot functions
- Changed default for 'smooth' in aggregate plots to `aspline`
- Required xperiment (experimental sandbox) `doc` types to explicitly set `n`, `d`, `m` to support multiple experimental sandboxes
- Changed `clean.figure` to `clean.fig` for stylistic consistency in `init`
- Changed calls to `filename` function to `file.path` for stylistic consistency
- Set default for `clean` to `FALSE` for all `doc` types; setting it `TRUE` for `doc=readme` simplified README document but complicated interactive use
- Set default for `clean.memlist` to `TRUE`; setting it based on `clean` led to hard-to-find bugs caused by stale data in memlist cache
- Removed ability for a single `figfun` call to draw multiple figures; doesn't work with new scheme for saving figures and I no longer use this feature

## Release 1.00 2018-07-27

Supports first draft blog post [Systematic Replication Has Limited Power to Detect Bad Science](https://natgoodman.github.io/repwr/doc.nnn/repwr.1.00.html) (`repwr.Rmd`) sent to external readers for feedback.


## Release 0.93 2018-07-25

Release candidate

This version is nearly a complete rewrite of the previous version.  Some highlights are

- Removed obsolete scripts including `R/scope.R` and `R/distr.R`
- Added `R/repwr.R` and many other scripts
- For data, added current top-level files needed for analysis and plotting. Did not add data subdirectories as these are huge (261MB for m=1e3, 980MB for m=1e4) and not needed once the simulation is done

## Release 0.92 2018-01-01

### scope.R

- Added `plot_cross`, `plot_pclose1`
- Integrated `d2t` probability functions from `distr.R`
- Systematically precomputed useful data tables: `d1`, `d33`, `dcross`, `dsig`, `dclose`, `dcrit`

### distr.R

- Added `pval2t`, `pval2d` functions
- Corrected usage of `lower.tail` parameter in `d2t` probability functions

## Release 0.91 2017-12-19

- Change sampling distribution from normal to noncentral t.
- Remove unused code.
- Clean up code for translating Cohen's d to t-statistic and t-distribution; simplify function names.

## Release 0.90 2017-12-07

First version. Ready for feedback from external readers.

## Copyright & License

Copyright (c) 2017-2018 Nathan Goodman

The software is **open source and free**, released under the [MIT License](https://opensource.org/licenses/MIT). The documentation is **open access**, released under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0).
